/**
 * Fleet report for managers, partners or a change board: Markdown for
 * reading, CSV for spreadsheets. Built from what the plugin already has.
 */
import { formatBytes } from './quantity';
import { fleetTotals, rollupByTenant, versionSpread } from './summary';
import { FleetCluster, Issue, Scorecard } from './types';

export interface ReportInput {
  clusters: FleetCluster[];
  issues: Issue[];
  scores: Map<string, Scorecard>;
  now: Date;
  title?: string;
}

function cell(v: unknown): string {
  return String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

export function fleetReportMarkdown({ clusters, issues, scores, now, title }: ReportInput): string {
  const t = fleetTotals(clusters);
  const lines: string[] = [];
  lines.push(`# ${title ?? 'VKS fleet report'}`, '', `Generated ${now.toISOString().replace('T', ' ').slice(0, 16)} UTC.`, '');
  lines.push('## Summary', '');
  lines.push(`- Clusters: ${t.clusters} across ${t.tenants} tenant${t.tenants === 1 ? '' : 's'}; ${t.healthy} healthy, ${t.attention} need attention, ${t.upgrading} upgrading.`);
  lines.push(`- Node capacity: ${t.cpus} vCPU, ${formatBytes(t.memoryBytes)} memory.`);
  const crit = issues.filter(i => i.severity === 'critical').length;
  const warn = issues.filter(i => i.severity === 'warning').length;
  lines.push(`- Issues: ${crit} critical, ${warn} warning${warn === 1 ? '' : 's'}.`);
  lines.push(`- Upgrades available: ${t.upgradable}.`);
  const avg = scores.size ? Math.round(Array.from(scores.values()).reduce((n, s) => n + s.score, 0) / scores.size) : undefined;
  if (avg !== undefined) lines.push(`- Average best-practice score: ${avg}/100.`);
  lines.push('');

  const actionable = issues.filter(i => i.severity !== 'info');
  if (actionable.length) {
    lines.push('## Issues needing action', '', '| Severity | Where | Issue | What to do |', '|---|---|---|---|');
    for (const i of actionable) lines.push(`| ${i.severity} | ${cell(i.clusterName ?? `Supervisor ${i.supervisorId}`)} | ${cell(i.title)} | ${cell(i.fix)} |`);
    lines.push('');
  }

  lines.push('## Clusters', '', '| Cluster | Tenant | Health | Kubernetes | Upgrade | Nodes | vCPU | Memory | Score |', '|---|---|---|---|---|---|---|---|---|');
  for (const c of [...clusters].sort((a, b) => a.tenantName.localeCompare(b.tenantName) || a.name.localeCompare(b.name))) {
    const nodes = c.machines.filter(m => !m.deletingSince).length;
    lines.push(
      `| ${cell(c.name)} | ${cell(c.tenantName)} | ${c.health}${c.upgrading ? ' (upgrading)' : ''} | ${cell(c.kubernetesVersion ?? '')} | ${cell(
        c.availableUpgrade?.version ?? '—'
      )} | ${nodes} | ${c.capacity?.cpus ?? '—'} | ${c.capacity ? formatBytes(c.capacity.memoryBytes) : '—'} | ${scores.get(c.key)?.score ?? '—'} |`
    );
  }
  lines.push('');

  const tenants = rollupByTenant(clusters);
  if (tenants.length > 1) {
    lines.push('## Tenants', '', '| Tenant | Clusters | Need attention | Upgrades available | vCPU | Memory |', '|---|---|---|---|---|---|');
    for (const r of tenants) {
      lines.push(`| ${cell(r.tenantName)} | ${r.clusters} | ${r.attention} | ${r.upgradable} | ${r.cpus} | ${formatBytes(r.memoryBytes)} |`);
    }
    lines.push('');
  }

  lines.push('## Kubernetes versions', '', '| Version | Clusters |', '|---|---|');
  for (const v of versionSpread(clusters)) lines.push(`| ${cell(v.version)} | ${v.count} |`);
  lines.push('', '_Generated by the vks-fleet Headlamp plugin._');
  return lines.join('\n');
}

function csvField(v: unknown): string {
  const s = String(v ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function fleetReportCsv({ clusters, issues, scores }: ReportInput): string {
  const header = [
    'supervisor', 'namespace', 'cluster', 'tenant', 'tenant_id', 'health', 'upgrading', 'kubernetes', 'upgrade_available',
    'class', 'control_plane', 'workers', 'nodes', 'vcpu', 'memory_gib', 'certificates_expire', 'score', 'critical_issues', 'warning_issues',
  ];
  const rows = clusters.map(c => {
    const mine = issues.filter(i => i.clusterKey === c.key);
    return [
      c.supervisorId, c.namespace, c.name, c.tenantName, c.tenantId, c.health, c.upgrading, c.kubernetesVersion ?? '',
      c.availableUpgrade?.version ?? '', c.clusterClass ?? '',
      c.controlPlane ? `${c.controlPlane.ready}/${c.controlPlane.desired}` : '', c.workers ? `${c.workers.ready}/${c.workers.desired}` : '',
      c.machines.filter(m => !m.deletingSince).length, c.capacity?.cpus ?? '',
      c.capacity ? (c.capacity.memoryBytes / 2 ** 30).toFixed(1) : '', c.certificatesExpiry ?? '', scores.get(c.key)?.score ?? '',
      mine.filter(i => i.severity === 'critical').length, mine.filter(i => i.severity === 'warning').length,
    ].map(csvField).join(',');
  });
  return [header.join(','), ...rows].join('\n');
}

/** Saves text as a file in the browser. */
export function download(filename: string, text: string, type: string): void {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}
